// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUFTmMN9Q3YfXIjwV6LaQEZeMq8lhKk3M',
    appId: '1:50384876745:web:aaa853432aac6e1bf80918',
    messagingSenderId: '50384876745',
    projectId: 'zeroapp-4979d',
    authDomain: 'zeroapp-4979d.firebaseapp.com',
    storageBucket: 'zeroapp-4979d.appspot.com',
    measurementId: 'G-ZR4QJ07PMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJgvi8b32uBXWOpIKBc3jL__HslcA2cYI',
    appId: '1:50384876745:android:302e1191236da69df80918',
    messagingSenderId: '50384876745',
    projectId: 'zeroapp-4979d',
    storageBucket: 'zeroapp-4979d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA97Bb8CQ7jHQ1xSlrNH70I6kZ7AvxKUCw',
    appId: '1:50384876745:ios:3b76d07ffa19d024f80918',
    messagingSenderId: '50384876745',
    projectId: 'zeroapp-4979d',
    storageBucket: 'zeroapp-4979d.appspot.com',
    iosBundleId: 'com.example.kindo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA97Bb8CQ7jHQ1xSlrNH70I6kZ7AvxKUCw',
    appId: '1:50384876745:ios:a9d604ee35aea433f80918',
    messagingSenderId: '50384876745',
    projectId: 'zeroapp-4979d',
    storageBucket: 'zeroapp-4979d.appspot.com',
    iosBundleId: 'com.example.kindo.RunnerTests',
  );
}
